scrape_configs:
  - job_name: swarm-service-endpoints
    file_sd_configs:
      - files:
        - /etc/swarm-endpoints/swarm-endpoints.json
    relabel_configs:
      # Set the instance to the hostname
      - source_labels: [__meta_swarm_node_hostname]
        target_label: instance
      # scrap only running tasks  
      - source_labels: [__meta_swarm_task_desired_state]
        regex: running
        action: keep
      # Add a task label
      - source_labels: [__meta_swarm_task_name]
        target_label: task
