scrape_configs:
  - job_name: swarm-service-endpoints
    file_sd_configs:
      - files:
        - /etc/swarm-endpoints/swarm-endpoints.json
    relabel_configs:
      # Set the instance to the hostname
      - source_labels: [__meta_swarm_node_hostname]
        target_label: instance
      # scrap only running tasks  
      - source_labels: [__meta_swarm_task_desired_state]
        regex: running
        action: keep
      # Remove the stack name from the job. ie, converts p_prometheus in prometheus
      - source_labels: [job]
        regex:        (.*?)_(.*)
        target_label: job
        replacement:  ${2}
        action:       replace  
      # Add a task label
      - source_labels: [__meta_swarm_task_name]
        target_label: task
