version: '3.3'

services:
  swarm-discover:
    image: jmendiara/prometheus-swarm-discovery
    command: ["-i", "5", "-o", "/swarm-endpoints/swarm-endpoints.json", "-p" , "prometheus_prometheus"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - swarm-endpoints:/swarm-endpoints/
    deploy:
      labels:
       - prometheus.disable=true
      placement:
        constraints:
          - node.role == manager
  prometheus:
    image: prom/prometheus:v1.8.2
    ports:
      - '9090:9090'
   
    volumes:
      - swarm-endpoints:/etc/swarm-endpoints/
    command: ["-storage.local.retention=2h", "-storage.local.memory-chunks=1048576", "-config.file=/etc/prometheus/prometheus.yaml"]
    deploy:
      labels:
       - prometheus.port=9090
       - prometheus.endpoint=/metrics
      placement:
        constraints:
          - node.role == manager
    configs:
      - source: prometheus
        target: /etc/prometheus/prometheus.yaml

volumes:
  swarm-endpoints:

configs: 
  prometheus:
    file: ./prometheus-configs/prometheus.yaml
